site_name: Yuru.Studio
site_descpiption: "ダンボールの隅"
site_author: "Yuru Studio"
site_url: "https://yuru.studio"

copyright: "Copyright © 2021 Yuru Studio"

theme:
  name: "material"

nav:
  - Home: "index.md"