site_name: Yuru.Studio
site_descpiption: 'ダンボールの隅'
site_author: 'Yuru Studio'
site_url: 'https://yuru.studio'

copyright: 'Copyright © 2021 Yuru Studio'

theme:
  name: 'material'
  locale: jp
  palette:
    primary: cyan
    accent: lime
  font:
    text: Mono


nav:
  - Home: 'index.md'
  - Member:
    - 七尾伶: 'Rei_Nanao/index.md'

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - codehilite